version: '3.8'
services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - ./data/pg_data/:/var/lib/postgresql/data
    ports:
      - 5432:5432
  frontend_react:
    image: node:latest
    working_dir: /app
    command: "npm run start"
    volumes:
      - ./frontend_react:/app
    ports:
      - 3000:3000
    depends_on:
      - db
  backend:
    image: backend
    build: ./backend
    working_dir: /var/www/
    volumes:
      - ./backend/:/var/www/
      - ./backend/public/:/var/www/html/
    ports:
      - 8200:80
    depends_on:
      - db